using HrSystem.Application.Abstractions;
using HrSystem.Application.Attendance;
using HrSystem.Application.Overtime;
using HrSystem.Domain.Entities;
using HrSystem.Domain.Repositories;

namespace HrSystem.Application.Services;

public sealed class OvertimeService(
    IAttendanceRecordRepository attendanceRecords,
    IOvertimeRequestRepository overtimeRequests,
    IRepository<OvertimePolicy> policies,
    ILeaveCalendarService calendar) : IOvertimeService
{
    public async Task<OvertimePolicy> GetActivePolicyAsync(CancellationToken cancellationToken = default)
    {
        var list = await policies.ListAsync(cancellationToken);
        var policy = list
            .OrderByDescending(x => x.EffectiveFrom)
            .ThenByDescending(x => x.Id)
            .FirstOrDefault();

        return policy ?? new OvertimePolicy
        {
            EffectiveFrom = DateOnly.FromDateTime(DateTime.UtcNow.Date),
            NormalMultiplier = 1.0m,
            HolidayMultiplier = 2.0m,
            ApprovalLevelsRequired = 1
        };
    }

    public async Task<OvertimeAutoGenerationResultDto> AutoGenerateFromAttendanceAsync(
        DateOnly fromInclusive,
        DateOnly toInclusive,
        bool createIfMissing = true,
        CancellationToken cancellationToken = default)
    {
        if (toInclusive < fromInclusive)
        {
            throw new ArgumentException("toInclusive must be >= fromInclusive");
        }

        var policy = await GetActivePolicyAsync(cancellationToken);
        var records = await attendanceRecords.ListByDateRangeAsync(fromInclusive, toInclusive, cancellationToken);
        var items = new List<OvertimeAutoGeneratedItemDto>();
        var created = 0;

        foreach (var record in records)
        {
            if (record.CheckInTime is null || record.CheckOutTime is null || record.Shift is null)
            {
                continue;
            }

            var workedMinutes = record.WorkedMinutes ?? AttendanceMetrics.ComputeWorkedMinutes(
                record.CheckInTime.Value,
                record.CheckOutTime.Value,
                record.Shift.IsOvernight);

            if (workedMinutes <= 0)
            {
                continue;
            }

            var isHoliday = await calendar.IsHolidayAsync(record.Date, cancellationToken);
            var multiplier = isHoliday ? policy.HolidayMultiplier : policy.NormalMultiplier;

            var calculatedMinutes = 0;
            if (isHoliday)
            {
                calculatedMinutes = workedMinutes;
            }
            else if (record.Shift.RequiredWorkMinutes is int required && required > 0)
            {
                calculatedMinutes = Math.Max(0, workedMinutes - required);
            }

            if (calculatedMinutes <= 0)
            {
                continue;
            }

            var existing = await overtimeRequests.GetByEmployeeAndDateAsync(record.EmployeeId, record.Date, cancellationToken);
            if (existing is not null)
            {
                continue;
            }

            if (!createIfMissing)
            {
                continue;
            }

            var request = new OvertimeRequest
            {
                EmployeeId = record.EmployeeId,
                Date = record.Date,
                AttendanceRecordId = record.Id,
                IsHoliday = isHoliday,
                PayMultiplier = multiplier,
                CalculatedMinutes = calculatedMinutes,
                RequestedMinutes = calculatedMinutes,
                ApprovedMinutes = null,
                ApprovalLevelsRequired = Math.Max(1, policy.ApprovalLevelsRequired),
                ApprovalLevelsApproved = 0,
                Status = OvertimeRequestStatus.Pending
            };

            await overtimeRequests.AddAsync(request, cancellationToken);
            await overtimeRequests.SaveChangesAsync(cancellationToken);
            created += 1;

            items.Add(new OvertimeAutoGeneratedItemDto(
                request.EmployeeId,
                request.Date,
                record.Id,
                request.IsHoliday,
                request.PayMultiplier,
                request.CalculatedMinutes,
                request.Id));
        }

        return new OvertimeAutoGenerationResultDto(
            fromInclusive,
            toInclusive,
            AttendanceRecordsScanned: records.Count,
            RequestsCreated: created,
            items);
    }

    public async Task ApproveAsync(int overtimeRequestId, string decidedBy, string? note = null, CancellationToken cancellationToken = default)
    {
        var entity = await overtimeRequests.GetByIdAsync(overtimeRequestId, cancellationToken);
        if (entity is null)
        {
            throw new InvalidOperationException("Overtime request not found.");
        }

        if (entity.Status != OvertimeRequestStatus.Pending)
        {
            throw new InvalidOperationException("Only pending overtime requests can be approved.");
        }

        if (string.IsNullOrWhiteSpace(decidedBy))
        {
            decidedBy = "system";
        }

        var nextLevel = entity.ApprovalLevelsApproved + 1;
        if (nextLevel > Math.Max(1, entity.ApprovalLevelsRequired))
        {
            throw new InvalidOperationException("Approval levels already completed.");
        }

        entity.ApprovalSteps.Add(new OvertimeApprovalStep
        {
            OvertimeRequestId = entity.Id,
            Level = nextLevel,
            Decision = OvertimeApprovalDecision.Approved,
            DecidedAtUtc = DateTimeOffset.UtcNow,
            DecidedBy = decidedBy,
            Note = note
        });

        entity.ApprovalLevelsApproved = nextLevel;

        if (entity.ApprovalLevelsApproved >= Math.Max(1, entity.ApprovalLevelsRequired))
        {
            entity.Status = OvertimeRequestStatus.Approved;
            entity.DecisionAtUtc = DateTime.UtcNow;
            entity.DecisionBy = decidedBy;
            entity.DecisionNote = note;
            entity.ApprovedMinutes = Math.Max(0, entity.RequestedMinutes);
        }

        await overtimeRequests.UpdateAsync(entity, cancellationToken);
        await overtimeRequests.SaveChangesAsync(cancellationToken);
    }

    public async Task RejectAsync(int overtimeRequestId, string decidedBy, string? note = null, CancellationToken cancellationToken = default)
    {
        var entity = await overtimeRequests.GetByIdAsync(overtimeRequestId, cancellationToken);
        if (entity is null)
        {
            throw new InvalidOperationException("Overtime request not found.");
        }

        if (entity.Status != OvertimeRequestStatus.Pending)
        {
            throw new InvalidOperationException("Only pending overtime requests can be rejected.");
        }

        if (string.IsNullOrWhiteSpace(decidedBy))
        {
            decidedBy = "system";
        }

        var nextLevel = entity.ApprovalLevelsApproved + 1;
        if (nextLevel > Math.Max(1, entity.ApprovalLevelsRequired))
        {
            nextLevel = Math.Max(1, entity.ApprovalLevelsRequired);
        }

        entity.ApprovalSteps.Add(new OvertimeApprovalStep
        {
            OvertimeRequestId = entity.Id,
            Level = nextLevel,
            Decision = OvertimeApprovalDecision.Rejected,
            DecidedAtUtc = DateTimeOffset.UtcNow,
            DecidedBy = decidedBy,
            Note = note
        });

        entity.Status = OvertimeRequestStatus.Rejected;
        entity.DecisionAtUtc = DateTime.UtcNow;
        entity.DecisionBy = decidedBy;
        entity.DecisionNote = note;
        entity.ApprovedMinutes = 0;

        await overtimeRequests.UpdateAsync(entity, cancellationToken);
        await overtimeRequests.SaveChangesAsync(cancellationToken);
    }
}
