namespace HrSystem.Application.Overtime;

public sealed record OvertimeAutoGeneratedItemDto(
    int EmployeeId,
    DateOnly Date,
    int AttendanceRecordId,
    bool IsHoliday,
    decimal PayMultiplier,
    int CalculatedMinutes,
    int OvertimeRequestId);

public sealed record OvertimeAutoGenerationResultDto(
    DateOnly FromInclusive,
    DateOnly ToInclusive,
    int AttendanceRecordsScanned,
    int RequestsCreated,
    IReadOnlyList<OvertimeAutoGeneratedItemDto> Items);
